demo-tabla-crud
Maude-Killers/SmartTrade pull request #15
Opened 2024-03-14 14:00 UTC by Dasagho

- **añadido scripts de desarrollo**
- **eliminado modelo de prueba innecesario**
- **probando interfaces complejas**
- **agregado formulario de weatherforecast**
- **solucionado fallo de campo fecha en formulario**

2024-03-14 18:36 UTC, ASigness approved these changes
Todo genial :)

2024-03-14 22:20 UTC, Dasagho commented
Vale ya he creado un ejemplo completo de como crear editar recuperar y borrar una entidad, o como tambien se le conoce un CRUD.
Echadle un vistazo y comentadme que os parece trabajar asi ^^

2024-03-24 16:05 UTC, LeooSP requested changes
Faltan cambios >:c

2024-03-24 16:05 UTC, LeooSP commented on Frontend/components/TableRow.razor
> +    public WeatherForecast forecast { get; set; } = new WeatherForecast();
```C#
private async Task HandleDelete()
{
    await service.DeleteForecastAsync(forecast.Id);
    nav.NavigateTo("/");
    nav.NavigateTo("/fetchda");
    //nav.NavigateTo("/fetchda", true); se ve mas feo pero es mas limpio
}
```

2024-03-24 16:05 UTC, LeooSP commented on Frontend/components/TableRow.razor
> +        <a href="#" class="font-medium text-red-600 dark:text-red-500 hover:underline ms-3">Remove</a>
```html
 <button @onclick="HandleDelete" class="font-medium text-red-600 dark:text-red-500 hover:underline ms-3">Remove</button>`

2024-03-24 16:05 UTC, LeooSP commented on Frontend/components/TableRow.razor
> +<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
```C#
@inject WeatherForecastService service
@inject NavigationManager nav
```

2024-03-24 16:14 UTC, LeooSP approved these changes
Ahora si que si

2024-03-24 16:15 UTC, Dasagho commented
Este PR ha sido patrocinado por un hipopotamo con alas :fly:

2024-03-24 16:16 UTC, merged